defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: simple_objective
    storage: null
    n_trials: 20
    n_jobs: 1

    params:
      xs: choice(1, 5, 10)


agent:
  max_iterations: 5000
  log_interval: ${xs}
  policy: 
    actor_hidden_dims: [512, 256, 128]
